# Site settings
title: "ZamBlador"
description: ""
url: "https://elsanx.onrender.com"  # http://localhost:4000 

title_slog: "" # Home pge slog
title_sep: "" # Home
# verification
bing: "236E4BD2B43F6FE3AADE37B9599300C0"
yandex: "4ce24848e872ed60"
google: "MJavsVfNgoSoIIgbYKVm8LRnwlBeaYc6pfStJxxWBiM"
# encoding timezone
encoding: "utf-8"
timezone: UTC
# Build settings
baseurl: / # leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:slug.html
sitemap_limit: 150.0
# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"
exclude:
  - firebase.json
  - data.json
